url: https://arsenicandlies.com
baseurl: ""

# Site settings
title: Arsenic & Lies
email: arsenicandlies@polydactylgames.com
description: "Arsenic & Lies"


# Team names, titles and social links
people:
- name: Karolina Soltys
  pic: 1
  position: Designer
  social:      


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/arsenicandlies/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
