url: http://127.0.0.1:4000
baseurl:

# Site settings
title: Arsenic & Lies
email: arsenicandlies@polydactylgames.com
description: "Arsenic & Lies"


# Team names, titles and social links
people:
- name: Karolina Soltys
  pic: 1
  position: Designer
  social:
    - title: facebook
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty